version: 2.1

jobs:
  release:
    docker:
      - image: cimg/node:14.20
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

workflows:
  release-test:
    jobs:
      - release:
          filters:
            branches:
              only: main
