name: Heroku Review App

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  sync:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update Heroku
        uses: readmeio/heroku-review-app-action@main
        with:
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          pipeline_name: markdown
